%CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
%C                        JZXC.FOR                                     C
%CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
function X=JZXC(A,W,N)
for I=1:N
    X(I)=0;
    for J=1:N
        X(I)=X(I)+A(I,J)*W(J);
    end
end
end